# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'SDWebImageMAGPlugin' do
    
  pod 'SDWebImage', '5.0.2'
  pod 'SDWebImageWebPCoder'
  
end
